services:
  mongo:
    build: "./mongo"
    volumes:
      - '${DATA_PATH_HOST}/mongo:/data/db'
      - '${DATA_PATH_HOST}/mongo_config:/data/configdb'
    ports:
      - ${MONGODB_PORT}:27017

  laravel:
    build:
      context: './laravel'
      dockerfile: 'Dockerfile-${LARAVEL_VERSION}'
    tty: true
    environment:
      - DB_HOST=mongo
      - DB_USERNAME=root
      - privileged=${LARAVEL_PRIVILEGED}
    ports:
      - '${LARAVEL_HTTP_PORT}:3000'
    volumes:
      - '${APP_CODE_PATH_HOST}:/app'

